version: '3.8'

services:
  postgres-auth:
    image: postgres:16-alpine
    container_name: eventpass-postgres-auth
    restart: always
    environment:
      POSTGRES_DB: eventpass_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

volumes:
  postgres_auth_data: