version: '3.8'

services:
  postgres-auth:
    image: postgres:16-alpine
    container_name: eventpass-postgres-auth
    restart: always
    environment:
      POSTGRES_DB: eventpass_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-events:
    image: postgres:16-alpine
    container_name: eventpass-postgres-events
    restart: always
    environment:
      POSTGRES_DB: eventpass_events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_events_data:/var/lib/postgresql/data

  # Emulador de AWS SQS para entorno local
  localstack:
    image: localstack/localstack:3.4.0
    container_name: localstack-eventpass
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./scripts:/etc/localstack/init/ready.d

  redis:
    image: redis:7-alpine
    container_name: eventpass-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_auth_data:
  postgres_events_data:
  redis_data: