server:
  port: ${PORT:8083}

spring:
  datasource:
    url: ${ORDERS_DB_URL}
    username: ${ORDERS_DB_USERNAME}
    password: ${ORDERS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false

  cloud:
    aws:
      region:
        static: ${AWS_REGION}

      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

app:
  services:
    events:
      base-url: ${EVENTS_SERVICE_URL}

  sqs:
    queues:
      order-created: ${ORDER_CREATED_QUEUE:eventpass-orders-created-queue}
      order-completed: ${ORDER_COMPLETED_QUEUE:eventpass-orders-completed-queue}