spring:
  application:
    name: ms-auth

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: 2000ms

application:
  security:
    admin:
      email: ${ADMIN_EMAIL:admin@eventpass.cl}
      password: ${ADMIN_PASSWORD:Cambiame123!}

    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971}
      expiration: ${JWT_EXPIRATION:86400000} # 24 horas.
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 días.
      service-token:
        expiration: ${JWT_SERVICE_EXPIRATION:900000}

    services:
      ms-orders:
        client-id: ${MS_ORDERS_CLIENT_ID:eventpass-ms-orders}
        client-secret: ${MS_ORDERS_CLIENT_SECRET:cambiame-ms-orders-secret}

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
