server:
  port: 8082

spring:
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/eventpass_auth}
    username: ${AUTH_DB_USERNAME:postgres}
    password: ${AUTH_DB_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect