spring:
  application:
    name: ms-tickets

  threads:
    virtual:
      enabled: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

app:
  sqs:
    queues:
      order-completed: ${ORDER_COMPLETED_QUEUE}

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always